#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
source "$CMD_ROOT/common"

if [ $# -ne 1 ]
then
	_usage
fi

vm=$1
cons_f="$VM_DIR/vm/console"

if [ -f $cons_f ]
then
	cons=$(cat $VM_DIR/$vm/console)
	sudo minicom -D $cons
fi
