#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
source "$CMD_ROOT/common"

_find_pid() {
	ps aux | grep qemu | grep -v runsvdir | grep $vm | awk '{print $2}'
}

_is_vm() {
	local name=$1
	echo $name | grep -qe '^v'
}

for vm_dir in $VM_DIR/*
do
	vm=$(basename $vm_dir)
	#_is_vm $vm || continue
	echo -e -n "$vm\t"
	set +e
	pid=$(_find_pid $vm)
	if [ -z "$pid" ]; then
		echo "DOWN"
		continue
	fi
	ssh -n $vm 'pwd' > /dev/null 2>&1 && echo "UP" || echo "UNREACHABLE"
	set -e
done
