#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
SH_ROOT=$(dirname "$CMD_ROOT")
source "$SH_ROOT/boilerplate"

set -eua

if [ $# -ne 1 ]
then
	echo "usage: vm-cycle <vm>"
	exit 1
fi
vm=$1

rcli vm down $vm || true
rcli vm up $vm
