#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
SH_ROOT=$(dirname "$CMD_ROOT")
source "$SH_ROOT/boilerplate"

if [ $# -ne 1 ]
then
	_usage
fi

vm=$1

#TODO configurable vms dir
sudo -b /data/virt/$vm/run 2>&1 | awk '{print $5}' > /data/virt/$vm/console &
