#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
SH_ROOT=$(dirname "$CMD_ROOT")
source "$SH_ROOT/boilerplate"

if [ $# -ne 1 ]
then
	_usage
fi

vm=$1

# phony background sudo task to trigger pw prompt
# the qemu invocation gets piped and backgrounded, so it can't prompt
sudo -b echo ""
#TODO configurable vms dir
(sudo /data/virt/$vm/run | awk '{print $5}' > /data/virt/$vm/console) &
