#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
source "$CMD_ROOT/common"
FOREGROUND=0

_up_fg() {
	local vm=$1
	sudo --preserve-env=KERNEL_SRC,ZNS_IMG,ZNS_IOPS_WRITE,ZNS_ZONE_SIZE $VM_DIR/$vm/run
}

_up_bg() {
	local vm=$1
	# phony background sudo task to trigger pw prompt
	# the qemu invocation gets backgrounded, so it can't prompt
	sudo -b true
	# Serial console is a unix socket created by run (server=on,wait=off).
	# qemu's stdout/stderr go to qemu.log for debugging; the interactive
	# console is `rcli vm cons <vm>` (which screens socat into the socket).
	(sudo --preserve-env=KERNEL_SRC,ZNS_IMG,ZNS_IOPS_WRITE,ZNS_ZONE_SIZE $VM_DIR/$vm/run > /$VM_DIR/$vm/qemu.log 2>&1) &
}

_up_one() {
	local vm=$1
	if [ "$FOREGROUND" -eq 1 ]; then
		_up_fg $vm
	else
		_up_bg $vm
	fi
}

while getopts "f" o; do
    case "${o}" in
        f)
            FOREGROUND=1
            ;;
        *)
            _usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ $# -ne 1 ]
then
	_usage
fi

vm=$1

if [ $vm == "all" ]; then
	FOREGROUND=0
	for vm in $(rcli vm list | grep DOWN | awk '{print $1}'); do
		_up_one $vm
	done
else
	_up_one $vm
fi
