#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
SH_ROOT=$(dirname "$CMD_ROOT")
source "$SH_ROOT/boilerplate.sh"

set -eua

if [ $# -ne 1 ]
then
	_usage
fi
vm=$1

rcli vm ready $vm
ssh $vm
