##
# Noisy Nieghbor c program
#
# @file
# @version 0.1

all: big-read rand-read

big-read: big-read.c
	$(CC) $(CFLAGS) -o big-read big-read.c

rand-read: rand-read.c
	$(CC) $(CFLAGS) -o rand-read rand-read.c

clean:
	rm -f big-read rand-read
