#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
SH_ROOT=$(dirname "$DIR")
source "$SH_ROOT/boilerplate.sh"

FSTEST_CONFIG=~/fstest-config
FSTESTS=~/fstests
BTRFS_PROGS=~/btrfs-progs

if [ $# -ne 1 ]
then
	_usage
fi

ctx=$1
fstests_config=$ctx.config
fstests_branch="upstream"
progs_branch="master"
test_dev=/dev/tst/tst
mkfs_args=""

if [[ $ctx == "squota" ]]; then
    mkfs_args="-O squota"
fi

if [[ $ctx == "quota" ]]; then
    mkfs_args="-O quota"
fi

cd "$FSTESTS"
git switch $fstests_branch
git pull
cp "$FSTEST_CONFIG/$fstests_config" local.config
make

cd "$BTRFS_PROGS"
git switch $progs_branch
git pull
make clean
make

sudo ./mkfs.btrfs -f $mkfs_args $test_dev
