#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
SH_ROOT=$(dirname "$CMD_ROOT")
source "$SH_ROOT/boilerplate.sh"

if [ $# -ne 3 ]
then
	_usage
fi

subv=$1
dst_dir=$2
count=$3


for i in $(seq $count); do
	btrfs subvolume snapshot $subv $dst_dir/snap.$i >/dev/null 2>&1
done
