#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
DIR=$(dirname "$SCRIPT")
CMD_ROOT=$(dirname "$DIR")
SH_ROOT=$(dirname "$CMD_ROOT")
source "$SH_ROOT/boilerplate"

if [ $# -ne 1 ]
then
	_usage
fi

vm=$1

set +e
ready=0
while [ $ready -eq 0 ]
do
	ssh $vm 'pwd' > /dev/null 2>&1
	[ $? -eq 0 ] && ready=1
done
